version: 2
updates:
  - package-ecosystem: pip
    directory: "/functions/extract/"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/functions/get-url-category/"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/functions/iterations/"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/functions/pull-lookup-urls/"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/functions/push-iocs-to-zia/"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "actions/checkout"
        versions: [">=6.0.2"]
      - dependency-name: "actions/setup-python"
        versions: [">=6.1.0"]
      - dependency-name: "actions/upload-artifact"
        versions: [">=6.0.0"]
