name: Falcon-Zscaler Integration
parameters:
    actions:
        configuration:
            GetUrlCategory:
                properties:
                    urlCategoryConfiguredName:
                        required: false
            iterations_handler_7b9614a1:
                properties:
                    quantity:
                        required: false
provision_on_install: true
trigger:
    next:
        - CreateVariable2
    type: On demand
actions:
    CreateVariable2:
        next:
            - GetUrlCategory
        id: 702d15788dbbffdf0b68d8e2f3599aa4
        class: CreateVariable
        properties:
            variable_schema:
                properties:
                    UrlCategoryConfiguredName:
                        type: string
                    UrlCategoryID:
                        type: string
                    lookup_result_start_key:
                        type: string
                type: object
        version_constraint: ~1
    GetUrlCategory:
        next:
            - urlcategoryid_exists_urlcategoryconfiguredname_exists
        id: functions.get-url-category.get-url-category
        properties:
            apiDefinitionId: ZIA Cloud Service API
            apiOperationId: _GET_urlcategories_lite
        version_constraint: ~0
    UpdateVariable2:
        next:
            - iterations_handler_7b9614a1
        id: 6c6eab39063fa3b72d98c82af60deb8a
        class: UpdateVariable
        properties:
            WorkflowCustomVariable:
                UrlCategoryConfiguredName: ${data['GetUrlCategory.FaaS.get-url-category.get-url-category.urlCategoryConfiguredName']}
                UrlCategoryID: ${data['GetUrlCategory.FaaS.get-url-category.get-url-category.urlCategoryId']}
        version_constraint: ~1
    activate_changes_1c6055a6:
        id: api_integrations.ZIA Cloud Service API._POST__status_activate
        properties:
            json: '{}'
            params:
                header:
                    Content-Type: application/json
    iterations_handler_7b9614a1:
        next:
            - activity_7b9614a1_28fa_4a5b_b923_7ee07f42f792_faas_iterations_iterations_handler_offset_18bc5891
        id: functions.iterations.iterations-handler
        properties: {}
conditions:
    urlcategoryid_exists_urlcategoryconfiguredname_exists:
        next:
            - UpdateVariable2
        expression: GetUrlCategory.FaaS.get-url-category.get-url-category.urlCategoryId:!null+GetUrlCategory.FaaS.get-url-category.get-url-category.urlCategoryConfiguredName:!null
        display:
            - UrlCategoryId exists
            - UrlCategoryConfiguredName exists
loops:
    activity_7b9614a1_28fa_4a5b_b923_7ee07f42f792_faas_iterations_iterations_handler_offset_18bc5891:
        next:
            - activate_changes_1c6055a6
        for:
            input: iterations_handler_7b9614a1.FaaS.iterations.iterations-handler.offset
            continue_on_partial_execution: false
            sequential: true
        trigger:
            next:
                - PullLookupUrls
        actions:
            ExtractHandler2:
                next:
                    - PushIocsToZiaHandler2
                id: functions.extract.extract-handler
                properties:
                    json:
                        json:
                            list: ${data['PullLookupUrls.FaaS.pull-lookup-urls.pull-lookup-urls.lookup_results']}
                version_constraint: ~0
            PullLookupUrls:
                next:
                    - WriteToLogRepo2
                id: functions.pull-lookup-urls.pull-lookup-urls
                properties:
                    apiDefinitionId: ZIA Cloud Service API
                    apiOperationId: _POST__urllookup
                    offset: ${iterations_handler_7b9614a1.FaaS.iterations.iterations-handler.offset.#}
                version_constraint: ~0
            PushIocsToZiaHandler2:
                next:
                    - WriteToLogRepo3
                id: functions.push-iocs-to-zia.push-iocs-to-zia-handler
                properties:
                    action: ADD_TO_LIST
                    apiDefinitionId: ZIA Cloud Service API
                    apiOperationId: _PUT__urlcategories
                    categoryID: ${data['WorkflowCustomVariable.UrlCategoryID']}
                    configuredName: ${data['WorkflowCustomVariable.UrlCategoryConfiguredName']}
                    customCategory: "TRUE"
                    superCategory: USER_DEFINED
                    urls:
                        - ${ExtractHandler2.FaaS.extract.extract-handler.urls}
                version_constraint: ~0
            WriteToLogRepo2:
                next:
                    - lookup_results_exists
                id: 0ec68880256f6192b9abef766d31fb04
                properties:
                    custom_json:
                        errors: ${data['PullLookupUrls.FaaS.pull-lookup-urls.pull-lookup-urls.errors']}
                        lookup_result: ${data['PullLookupUrls.FaaS.pull-lookup-urls.pull-lookup-urls.lookup_results']}
                        type: pull-lookup-urls-result
                        urls: ${data['PullLookupUrls.FaaS.pull-lookup-urls.pull-lookup-urls.urls']}
                    foundry_app_id: ${{FOUNDRY_APP_ID}}
                version_constraint: ~1
            WriteToLogRepo3:
                id: 0ec68880256f6192b9abef766d31fb04
                properties:
                    custom_json:
                        errors: ${data['PushIocsToZiaHandler2.FaaS.push-iocs-to-zia.push-iocs-to-zia-handler.errors']}
                        lookup_result: ${data['PullLookupUrls.FaaS.pull-lookup-urls.pull-lookup-urls.lookup_results']}
                        type: push-iocs-to-zia-result
                        urlCategoryConfiguredName: ${data['PushIocsToZiaHandler2.FaaS.push-iocs-to-zia.push-iocs-to-zia-handler.urlCategoryConfiguredName']}
                        urlCategoryId: ${data['PushIocsToZiaHandler2.FaaS.push-iocs-to-zia.push-iocs-to-zia-handler.urlCategoryId']}
                        urls: ${data['PushIocsToZiaHandler2.FaaS.push-iocs-to-zia.push-iocs-to-zia-handler.urls']}
                    foundry_app_id: ${{FOUNDRY_APP_ID}}
                version_constraint: ~1
        conditions:
            lookup_results_exists:
                next:
                    - ExtractHandler2
                expression: PullLookupUrls.FaaS.pull-lookup-urls.pull-lookup-urls.lookup_results:!null
                display:
                    - Lookup results exists
